apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trend-frontend
  template:
    metadata:
      labels:
        app: trend-frontend
    spec:
      containers:
        - name: frontend
          image: tamililan/trend-react:latest
          ports:
            - containerPort: 80
